-- ==========================================
-- 1. EXTENSIONES Y LIMPIEZA TOTAL EN CASCADA
-- ==========================================
create extension if not exists "uuid-ossp";

drop view if exists public.panel_administrador_alertas cascade;
drop table if exists public.calificaciones cascade;
drop table if exists public.reportes_asistencia cascade;
drop table if exists public.historial_strikes cascade;
drop table if exists public.mensajes cascade;
drop table if exists public.participantes cascade;
drop table if exists public.actividades cascade;
drop table if exists public.perfiles cascade;
drop table if exists public.resenas_actividades cascade;
-- ==========================================
-- 2. CREACIÓN DE TABLAS (MVP SINCRONIZADO)
-- ==========================================

create table public.perfiles (
    id uuid references auth.users on delete cascade primary key,
    nombre text not null,
    carrera text not null,
    tasa_asistencia int2 not null default 100 check (tasa_asistencia >= 0 and tasa_asistencia <= 100),
    reputacion_stars numeric(2,1) not null default 5.0 check (reputacion_stars >= 1.0 and reputacion_stars <= 5.0),
    strikes int2 not null default 0 check (strikes >= 0 and strikes <= 3),
    estado text not null default 'activo' check (estado in ('activo', 'suspendido', 'bloqueado')),
    es_admin boolean not null default false,
    fecha_registro timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.actividades (
    id bigint generated by default as identity primary key,
    creador_id uuid references public.perfiles(id) on delete cascade not null,
    titulo text not null check (char_length(titulo) >= 5 and char_length(titulo) <= 100),
    categoria text not null check (categoria in ('Deportes', 'Estudio', 'Ocio', 'Proyectos')),
    fecha_hora timestamp with time zone not null,
    duracion_horas int2 not null default 2 check (duracion_horas in (1, 2, 3, 4, 6, 8)), -- Sincronizado con duración numérica de la app
    lugar text not null check (char_length(lugar) >= 3),
    cupos_min int2 not null default 2 check (cupos_min >= 2),
    cupos_max int2 not null check (cupos_max >= 2 and cupos_max <= 30),
    estado text not null default 'abierto' check (estado in ('abierto', 'confirmado', 'finalizado', 'cancelado')),
    recompensa text default 'Gratis' check (char_length(recompensa) <= 150),
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint check_quorum_coherente check (cupos_min <= cupos_max)
);

create table public.participantes (
    id bigint generated by default as identity primary key,
    actividad_id bigint references public.actividades(id) on delete cascade not null,
    usuario_id uuid references public.perfiles(id) on delete cascade not null,
    rol text not null default 'asistente' check (rol in ('organizador', 'asistente')),
    estado_asistencia text not null default 'pendiente' check (estado_asistencia in ('pendiente', 'asistio', 'planton')),
    fecha_union timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint unica_participacion unique (actividad_id, usuario_id)
);

create table public.mensajes (
    id bigint generated by default as identity primary key,
    actividad_id bigint references public.actividades(id) on delete cascade not null,
    usuario_id uuid references public.perfiles(id) on delete cascade not null,
    contenido text not null check (char_length(contenido) >= 1 and char_length(contenido) <= 500),
    fecha_envio timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.historial_strikes (
    id bigint generated by default as identity primary key,
    usuario_id uuid references public.perfiles(id) on delete cascade not null,
    actividad_id bigint references public.actividades(id) on delete set null,
    motivo text not null check (char_length(motivo) >= 10),
    fecha_emision timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.reportes_asistencia (
    id bigint generated by default as identity primary key,
    reportante_id uuid references public.perfiles(id) on delete cascade not null,
    reportado_id uuid references public.perfiles(id) on delete cascade not null,
    actividad_id bigint references public.actividades(id) on delete cascade not null,
    detalles text not null check (char_length(detalles) >= 15),
    revisado_por_admin boolean default false not null,
    fecha_reporte timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint unico_reporte_por_evento unique (reportante_id, reportado_id, actividad_id)
);

create table public.calificaciones (
    id bigint generated by default as identity primary key,
    actividad_id bigint references public.actividades(id) on delete cascade not null,
    calificador_id uuid references public.perfiles(id) on delete cascade not null,
    tipo text not null default 'actividad' check (tipo in ('actividad', 'usuario')),
    calificado_id uuid references public.perfiles(id) on delete cascade not null, -- ID del Organizador evaluado
    puntuacion int2 not null check (puntuacion >= 1 and puntuacion <= 3), -- Mapeado del RatingModal de la app
    fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint unica_calificacion_por_evento unique (actividad_id, calificador_id, tipo)
);

-- ==========================================
-- 3. INDEXACIÓN Y SEGURIDAD AVANZADA (RLS)
-- ==========================================
create index idx_actividades_estado_fecha on public.actividades(estado, fecha_hora);
create index idx_participantes_actividad on public.participantes(actividad_id);
create index idx_mensajes_actividad_fecha on public.mensajes(actividad_id, fecha_envio);
create index idx_strikes_usuario on public.historial_strikes(usuario_id);

alter table public.perfiles enable row level security;
alter table public.actividades enable row level security;
alter table public.participantes enable row level security;
alter table public.calificaciones enable row level security;
alter table public.mensajes enable row level security;
alter table public.historial_strikes enable row level security;
alter table public.reportes_asistencia enable row level security;

-- Políticas de Seguridad
create policy "Ver perfiles" on public.perfiles for select using (auth.role() = 'authenticated');
create policy "Modificar propio perfil" on public.perfiles for update using (auth.uid() = id);

create policy "Ver tablón" on public.actividades for select using (auth.role() = 'authenticated');
create policy "Publicar actividades" on public.actividades for insert with check (auth.uid() = creador_id);
create policy "Actualizar propia actividad" on public.actividades for update using (auth.uid() = creador_id);

create policy "Ver participantes" on public.participantes for select using (auth.role() = 'authenticated');
create policy "Unirse a actividades" on public.participantes for insert with check (auth.uid() = usuario_id);
create policy "Actualizar participantes" on public.participantes for update using ((select creador_id from public.actividades where id = actividad_id) = auth.uid());
create policy "Salir o remover de actividad" on public.participantes for delete using (auth.uid() = usuario_id or (select creador_id from public.actividades where id = actividad_id) = auth.uid());

create policy "Permitir calificar" on public.calificaciones for insert with check (auth.uid() = calificador_id);
create policy "Ver calificaciones" on public.calificaciones for select using (auth.role() = 'authenticated');

create policy "Ver propios strikes" on public.historial_strikes for select using (auth.uid() = usuario_id);
create policy "Insertar reportes" on public.reportes_asistencia for insert with check (auth.uid() = reportante_id);
create policy "Ver propios reportes" on public.reportes_asistencia for select using (auth.uid() = reportante_id or auth.uid() = reportado_id);

create policy "Leer chat" on public.mensajes for select using (
    (select estado from public.perfiles where id = auth.uid()) = 'activo'
    and exists (select 1 from public.participantes where participantes.actividad_id = mensajes.actividad_id and participantes.usuario_id = auth.uid())
);

create policy "Escribir en chat" on public.mensajes for insert with check (
    auth.uid() = usuario_id 
    and (select estado from public.perfiles where id = auth.uid()) = 'activo'
    and exists (select 1 from public.participantes where participantes.actividad_id = mensajes.actividad_id and participantes.usuario_id = auth.uid())
);

-- ==========================================
-- 4. TRIGGERS (EL MOTOR LOGÍSTICO COMPLETO)
-- ==========================================

-- TRIGGER 1: Registro Exclusivo UCSP
create or replace function public.crear_perfil_nuevo_usuario() returns trigger as $$
begin
    if lower(new.email) not like '%@ucsp.edu.pe' then raise exception 'Solo correos @ucsp.edu.pe'; end if;
    insert into public.perfiles (id, nombre, carrera) values (new.id, coalesce(new.raw_user_meta_data->>'nombre', 'Estudiante UCSP'), coalesce(new.raw_user_meta_data->>'carrera', 'Por Definir'));
    return new;
end; $$ language plpgsql security definer;
create trigger tr_crear_perfil_nuevo_usuario after insert on auth.users for each row execute function public.crear_perfil_nuevo_usuario();

-- TRIGGER 2: Auto-matricular Organizador
create or replace function public.auto_agregar_organizador() returns trigger as $$
begin
    insert into public.participantes (actividad_id, usuario_id, rol, estado_asistencia) values (new.id, new.creador_id, 'organizador', 'asistio');
    return new;
end; $$ language plpgsql security definer;
create trigger tr_auto_agregar_organizador after insert on public.actividades for each row execute function public.auto_agregar_organizador();

-- TRIGGER 3: Procesamiento Analítico de Tasa de Asistencia
create or replace function public.actualizar_tasa_asistencia() returns trigger as $$
declare v_total int; v_asistencias int; v_tasa int2;
begin
    select count(*) into v_total from public.participantes where usuario_id = new.usuario_id and estado_asistencia in ('asistio', 'planton');
    select count(*) into v_asistencias from public.participantes where usuario_id = new.usuario_id and estado_asistencia = 'asistio';
    if v_total > 0 then v_tasa := round((v_asistencias::numeric / v_total::numeric) * 100); else v_tasa := 100; end if;
    update public.perfiles set tasa_asistencia = v_tasa where id = new.usuario_id;
    return new;
end; $$ language plpgsql security definer;
create trigger tr_actualizar_tasa_asistencia after update of estado_asistencia on public.participantes for each row when (new.estado_asistencia in ('asistio', 'planton')) execute function public.actualizar_tasa_asistencia();

-- TRIGGER 4: Conversión de Reputación Decimal a Escala de Estrellas (1.0 - 5.0)
create or replace function public.actualizar_reputacion_organizador() returns trigger as $$
declare v_promedio numeric; v_estrellas numeric(2,1);
begin
    select avg(puntuacion) into v_promedio from public.calificaciones where calificado_id = new.calificado_id and tipo = 'actividad';
    if v_promedio is not null then v_estrellas := round((((v_promedio - 1.0) / 2.0) * 4.0 + 1.0)::numeric, 1); else v_estrellas := 5.0; end if;
    update public.perfiles set reputacion_stars = v_estrellas where id = new.calificado_id;
    return new;
end; $$ language plpgsql security definer;
create trigger tr_actualizar_reputacion_organizador after insert or update on public.calificaciones for each row execute function public.actualizar_reputacion_organizador();

-- TRIGGER 5: Auditoría y Baneo Automático por Acumulación de Strikes
create or replace function public.procesar_y_banear_usuario() returns trigger as $$
declare v_total_strikes int2;
begin
    select count(*)::int2 into v_total_strikes from public.historial_strikes where usuario_id = new.usuario_id;
    update public.perfiles set strikes = v_total_strikes where id = new.usuario_id;
    if v_total_strikes >= 3 then
        update public.perfiles set estado = 'bloqueado' where id = new.usuario_id;
    end if;
    return new;
end; $$ language plpgsql security definer;
create trigger tr_procesar_y_banear_usuario after insert on public.historial_strikes for each row execute function public.procesar_y_banear_usuario();

-- ==========================================
-- 5. PROCEDIMIENTOS ALMACENADOS (RPC)
-- ==========================================

-- RPC A: Inscripción Concurrentemente Segura (Bloqueo Pesimista)
create or replace function public.unirse_a_actividad_concurrente(p_actividad_id bigint, p_usuario_id uuid) returns json as $$
declare v_max int2; v_actuales bigint; v_estado text; v_user_estado text;
begin
    select estado into v_user_estado from public.perfiles where id = p_usuario_id;
    if v_user_estado <> 'activo' then return json_build_object('success', false, 'message', 'Cuenta no activa'); end if;

    select cupos_max, estado into v_max, v_estado from public.actividades where id = p_actividad_id for update;
    if v_estado <> 'abierto' then return json_build_object('success', false, 'message', 'Cerrada'); end if;
    
    select count(*) into v_actuales from public.participantes where actividad_id = p_actividad_id;
    if v_actuales >= v_max then return json_build_object('success', false, 'message', 'Llena'); end if;
    
    insert into public.participantes (actividad_id, usuario_id, rol) values (p_actividad_id, p_usuario_id, 'asistente');
    return json_build_object('success', true, 'message', 'Unido');
end; $$ language plpgsql security definer;

-- RPC B: Resolución y Despacho Administrativo de Denuncias
create or replace function public.resolver_reporte_incidencia(p_reporte_id bigint, p_emitir_strike boolean, p_motivo text) returns json as $$
declare v_reportado_id uuid; v_actividad_id bigint;
begin
    if not exists (select 1 from public.perfiles where id = auth.uid() and es_admin = true) then
        return json_build_object('success', false, 'message', 'Acceso denegado: Requiere rol es_admin.');
    end if;

    select reportado_id, actividad_id into v_reportado_id, v_actividad_id from public.reportes_asistencia where id = p_reporte_id;
    if v_reportado_id is null then return json_build_object('success', false, 'message', 'Reporte inexistente'); end if;

    update public.reportes_asistencia set revisado_por_admin = true where id = p_reporte_id;

    if p_emitir_strike = true then
        insert into public.historial_strikes (usuario_id, actividad_id, motivo)
        values (v_reportado_id, v_actividad_id, coalesce(p_motivo, 'Falta comunitaria validada por administración.'));
    end if;

    return json_build_object('success', true, 'message', 'Resolución procesada de forma consistente.');
end; $$ language plpgsql security definer;

-- ==========================================
-- 6. PANEL DE AUDITORÍA (VISTAS INTEGRADAS)
-- ==========================================

create or replace view public.panel_administrador_alertas as
select 
    r.id as reporte_id,
    r.fecha_reporte,
    act.titulo as actividad_titulo,
    act.estado as actividad_estado,
    (select count(*) from public.participantes p where p.actividad_id = act.id) as total_asistentes,
    perf_nte.nombre as reportante_nombre,
    perf_do.nombre as reportado_nombre,
    perf_do.strikes as reportado_strikes_actuales,
    perf_do.estado as reportado_estado_cuenta,
    r.detalles as motivo_reporte,
    r.revisado_por_admin
from public.reportes_asistencia r
join public.actividades act on r.actividad_id = act.id
join public.perfiles perf_nte on r.reportante_id = perf_nte.id
join public.perfiles perf_do on r.reportado_id = perf_do.id;

alter view public.panel_administrador_alertas owner to postgres;
create policy "Vista de alertas para admins" on public.reportes_asistencia for select using ((select es_admin from public.perfiles where id = auth.uid()) = true);